apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance.control
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: attendance.control
  template:
    metadata:
      labels:
        app: attendance.control
    spec:
      containers:
        - name: attendance.control
          image: attendance.control:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: attendance.control-balancer
spec:
  selector:
    app: attendance.control
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
